image: cirrusci/flutter:3.32.8

stages:
  - test
  - build

variables:
  PUB_CACHE: .pub-cache

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .pub-cache/
    - .dart_tool/

before_script:
  - flutter pub get

test:
  stage: test
  script:
    - flutter doctor -v
    - flutter analyze
    - flutter test --coverage
  coverage: '/lines\.*: \d+\.\d+\%/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura.xml
    paths:
      - coverage/
    expire_in: 1 week
  only:
    - branches
    - merge_requests

build:android:
  stage: build
  script:
    - flutter build apk --debug
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-debug.apk
    expire_in: 1 week
  only:
    - main
    - develop
    - /^feature\/.*$/

build:web:
  stage: build
  script:
    - flutter build web --web-renderer html
  artifacts:
    paths:
      - build/web/
    expire_in: 1 week
  only:
    - main
    - develop
    - /^feature\/.*$/
