name: nihongo_flashcard
publish_to: "none"
version: 0.1.0+1
environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_it: ^7.6.4
  go_router: ^16.1.0
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.4
  intl: ^0.20.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.2
  flutter_markdown: ^0.7.3
  markdown_text_input: ^2.0.0

  # UI
  flutter_staggered_animations: ^1.1.1

  # Optional: icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  sqflite_common_ffi: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/presets/
